### ISSUE TITLE
Code not being highlighted + can't submit pull request

### ISSUE THREAD

**Issue by pfftdammitchris** [withspectrum/draft-js-prism-plugin#4]
I had a previous issue opened just 2 hours ago at:
https://github.com/withspectrum/draft-js-prism-plugin/issues/3

I had to make a new thread because it was closed and I cannot reply in it.
(Regarding that console.log issue tried to submit a pull request to remove that but the console.log() code wasn't found on the index.js file in the src folder. It seems to only exist in the index.js inside /dist/ ?

Also, code still isn't being highlighted even when starting out text with "```javascript"

Screenshot below:

![unhighlighted](https://user-images.githubusercontent.com/20717348/32966903-4110d05c-cb90-11e7-8aca-a8a59c4fd574.png)

### It seems to be loading the styles from the .css style but keywords like "function" or "const" or etc aren't being highlighted with colors. Its just all white.

I am using the [prism-okaidia.css](https://github.com/PrismJS/prism/blob/gh-pages/themes/prism-okaidia.css) stylesheet

**Comment by mxstbr** [comment]
Ohhh sorry, the triple backtick thing only applies if you're using `draft-js-markdown-plugin`! I just assumed you were using that because I'm using it, my bad 😅 

How are you creating those code blocks?

Essentially, you need to set `data.language` of the code block to the language you want to highlight as. (`draft-js-markdown-plugin` just does that when you do the triple backtick thing, that's why I mentioned it) Something like

```JS
const codeBlock = new ContentBlock({
    characterList: List(),
    depth: 0,
    key: 'somekey',
    text: "",
    type: 'code-block',
    data: Map({
      language: 'javascript'
    }),
})
```

(also, you can reply in closed threads perfectly fine)

**Comment by pfftdammitchris** [comment]
Oh I see. I thought that was a little odd.

This is how my code blocks are being created:

```
// @flow
import { EditorState, Modifier, RichUtils } from 'draft-js';

const toggleBlockType = (getEditorState: Function, onChange: Function) => {
  const editorState = getEditorState();
  const selectionState = editorState.getSelection();
  const isCollapsed = selectionState.isCollapsed();
  if (isCollapsed) {
    return onChange(RichUtils.toggleCode(getEditorState()));
  }
  // Convert "selected" text to code-blocks
  return onChange(
    EditorState.push(
      editorState,
      Modifier.setBlockType(editorState.getCurrentContent(), selectionState, 'code-block'),
      'change-block-type',
    ),
  );
};

```

I am also binding a ctrl + , (comma) key binding to execute code blocks with RichUtils:

```
    if (command === 'toggle-code') {
      onChange(RichUtils.toggleCode(editorState));
      return 'handled';
    }
```

Both ways still generate the same output styling as seen above.

Thx I'll take a look at the markdown source code and see if I can implement this.

p.s. Now I know I can reply to closed threads

**Comment by mxstbr** [comment]
You'll likely have to show users an input of some sort to let them input their desired language! Good luck :blush:
